<a href="https://colab.research.google.com/github/AbhiJ2706/tic-tac-toe-tensorflow-AI/blob/master/tictactoe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
from tensorflow import keras
#other libraries
import numpy as np
import random
import collections

print(tf.__version__)

2.4.0


In [3]:
#loading database
A = np.loadtxt("/content/drive/My Drive/data3.txt")
#separating questions from answers using columns
X = A[:,:9]      
y = A[:,9:]

#checks in each example which player (X or O) wins
def checkforWin(x, board):
    if board[0] == x and board[1] == x and board[2] == x: #win case
        tempBoard = [0, 1, 2] #array containing win case
        return 1, tempBoard #returns result and win case
    if board[3] == x and board[4] == x and board[5] == x:
        tempBoard = [3, 4, 5]
        return 2, tempBoard
    if board[6] == x and board[7] == x and board[8] == x:
        tempBoard = [6, 7, 8]
        return 3, tempBoard
    if board[0] == x and board[3] == x and board[6] == x:
        tempBoard = [0, 3, 6]
        return 4, tempBoard
    if board[1] == x and board[4] == x and board[7] == x:
        tempBoard = [1, 4, 7]
        return 5, tempBoard
    if board[2] == x and board[5] == x and board[8] == x:
        tempBoard = [2, 5, 8]
        return 6, tempBoard
    if board[0] == x and board[4] == x and board[8] == x:
        tempBoard = [0, 4, 8]
        return 7, tempBoard
    if board[2] == x and board[4] == x and board[6] == x:
        tempBoard = [2, 4, 6]
        return 8, tempBoard
    else:
        return 0

#going through cases and removing a winning move to create cases
for i in range(len(X)):
    #checking for error
    try:
        result, tempBoard = checkforWin(y[i], X[i]) #figuring out who wins
        if result > 0:
            j = random.randint(0,2)
            y[i] = tempBoard[j] #setting the answers to be the removed winning move
            X[i][int(y[i])] = 0 #removing a winning move
            a = collections.Counter(X[i]) #counting amount of each piece 
            x = a[1] #counting X's
            Y = a[-1] #counting O's
            if x == Y:
                #removing a random O so that it is O's turn
                indices = [k for k, x in enumerate(X[i]) if x == -1]
                l = random.randint(0,len(indices)-1)
                X[i][indices[l]] = 0          
    except TypeError:
        pass

newX = []
newY = []
#some cases return -1 as the answer. This removes them and replaces them with a viable case
for i in range(len(X)):
    if y[i] != -1:
        newX.append(X[i])
        newY.append(y[i])

newX = np.array(newX)
newY = np.array(newY)

(train_images, train_labels), (test_images, test_labels) = (newX, newY), (newX, newY) #making training & test cases

print(len(newX), y)


942 [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 0.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 0.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 2.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 1.]
 [ 2.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 2.]
 [ 1.]
 [ 2.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 2.]
 [ 2.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 2.]
 [ 1.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 0.]
 [ 3.]
 [ 0.]
 [ 0.]
 [ 6.]
 [ 0.]
 [ 6.]
 [ 0.]
 [ 4.]
 [ 0.]
 [ 8.]
 [ 7.]
 [ 1.]
 [ 4.]
 [ 7.]
 [ 8.]
 [ 4.]
 [ 8.]
 [ 1.]
 [ 4.]
 [ 4.]
 [ 7.]
 [ 0.]
 [ 6.]
 [ 6.]
 [ 3.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 1.]
 [ 4.]
 [ 7.]
 [ 0.]
 [ 4.]
 [ 4.]
 [ 3.]
 [ 8.]
 [ 6.]
 [ 6.]
 [ 0.]
 [ 0.]
 [ 3.]
 [ 0.]
 [ 6.]
 [ 5.]
 [ 2.]
 [ 8.]
 [ 4.]
 [ 8.]
 [ 4.]
 [ 6.]
 [ 2.]
 [ 4.]
 [ 0.]
 [ 8.]
 [ 2.]
 [ 8.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 8.]
 [ 8.]
 [ 4.]
 [ 4.]
 [

In [4]:
class_names = [0,1,2,3,4,5,6,7,8] #list of different possible answers

#neural network
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(9,)), #input layer
    keras.layers.Dense(18, activation=tf.nn.tanh), #hidden layer
    keras.layers.Dense(18, activation=tf.nn.tanh), #hidden layer
    keras.layers.Dense(9, activation=tf.nn.softmax) #output layer
])

#compiling neural network
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=["accuracy"])

#training model
model.fit(train_images, train_labels, epochs=2000)

#running tests (no learning occurs here)
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

#using network for predictions
predictions = model.predict(test_images)

#printing predictions
for i in range(15):
    print(np.round(predictions[i]*1000)/1000, np.argmax(predictions[i]), test_labels[i])

Epoch 1/2000
30/30 [==============================] - 1s 1ms/step - loss: 2.2768 - accuracy: 0.0907
Epoch 2/2000
30/30 [==============================] - 0s 1ms/step - loss: 2.2029 - accuracy: 0.1271
Epoch 3/2000
30/30 [==============================] - 0s 1ms/step - loss: 2.1736 - accuracy: 0.1527
Epoch 4/2000
30/30 [==============================] - 0s 1ms/step - loss: 2.1416 - accuracy: 0.1794
Epoch 5/2000
30/30 [==============================] - 0s 1ms/step - loss: 2.1336 - accuracy: 0.1974
Epoch 6/2000
30/30 [==============================] - 0s 1ms/step - loss: 2.1309 - accuracy: 0.1985
Epoch 7/2000
30/30 [==============================] - 0s 1ms/step - loss: 2.1053 - accuracy: 0.2032
Epoch 8/2000
30/30 [==============================] - 0s 1ms/step - loss: 2.1013 - accuracy: 0.2090
Epoch 9/2000
30/30 [==============================] - 0s 1ms/step - loss: 2.1013 - accuracy: 0.2181
Epoch 10/2000
30/30 [==============================] - 0s 1ms/step - loss: 2.0774 - accuracy: 0.2460

In [7]:
#board positions
board = [0,0,0,0,0,0,0,0,0]

#checking for a win in the actual tic tac toe game
def checkForWin(x):
    if board[0] == x and board[1] == x and board[2] == x:
        return True
    if board[3] == x and board[4] == x and board[5] == x:
        return True
    if board[6] == x and board[7] == x and board[8] == x:
        return True
    if board[0] == x and board[3] == x and board[6] == x:
        return True
    if board[1] == x and board[4] == x and board[7] == x:
        return True
    if board[2] == x and board[5] == x and board[8] == x:
        return True
    if board[0] == x and board[4] == x and board[8] == x:
        return True
    if board[2] == x and board[4] == x and board[6] == x:
        return True
    else:
        return False

print("X is 1, O is -1, empty spaces are 0")

#tictac toe game loop
def mainloop():
    mainloop = True
    while mainloop== True:
        x = np.array([board], dtype="float")
        print(x[0][0:3], "\n")
        print(x[0][3:6], "\n")
        print(x[0][6:9], "\n")
        i = int(input("Enter board pos: "))
        if board[i] == 0:
            board[i] = 1 #filling board position
            #drawing X
            #checks if either player won or draw
            xwin = checkForWin(1)
            ywin = checkForWin(-1)
            if xwin:
                print("X wins!")
                print(x[0][0:3], "\n")
                print(x[0][3:6], "\n")
                print(x[0][6:9], "\n")
                mainloop = False
                break
            elif 0 not in board and not ywin and not xwin:
                print("Draw!")
                mainloop = False
                break
            #neural network runs a prediction to get the best move
            predictions = model.predict(np.array([board], dtype="float"))
            space = np.argmax(predictions)
            board[space] = -1 #populating board
        #checking for win for O
        ywin = checkForWin(-1)
        x = np.array([board], dtype="float")
        if ywin:
            print(x[0][0:3], "\n")
            print(x[0][3:6], "\n")
            print(x[0][6:9], "\n")
            print("Y wins!")
            mainloop = False
            break
        if not mainloop:
            break

#putting everything together
while 1:
    mainloop();
    if input("Play again?: ") == "no":
        break;
    board = [0,0,0,0,0,0,0,0,0]

[0. 0. 0.] 

[0. 0. 0.] 

[0. 0. 0.] 

Enter board pos: 1
[ 0.  1. -1.] 

[0. 0. 0.] 

[0. 0. 0.] 

Enter board pos: 4
[ 0.  1. -1.] 

[0. 1. 0.] 

[ 0. -1.  0.] 

Enter board pos: 0
[ 1.  1. -1.] 

[0. 1. 0.] 

[-1. -1.  0.] 

Enter board pos: 3
[ 1.  1. -1.] 

[1. 1. 0.] 

[-1. -1. -1.] 

Y wins!


KeyboardInterrupt: ignored

In [ ]:
!pip install tensorflowjs

     |████████████████████████████████| 71kB 4.1MB/s 
     |████████████████████████████████| 112kB 6.8MB/s 
  Found existing installation: tensorflow-hub 0.10.0
    Uninstalling tensorflow-hub-0.10.0:
      Successfully uninstalled tensorflow-hub-0.10.0


In [ ]:
import tensorflowjs as tfjs

tfjs.converters.save_keras_model(model, '/content/drive/My Drive/doot')


/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/keras_h5_conversion.py:123: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  return h5py.File(h5file)
